site:
  name: OpenDance
  site: 'https://opendancemadeira.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: w6wgXfaMupm2O1UkIsTvdTlzRc49RF-6q8ZeEuJrc2I

# Default SEO metadata
metadata:
  title:
    default: OpenDance
    template: '%s — OpenDance'
  description: 'a escola de dança mais popular e na moda na Madeira, especializada em danças Latinas, Afro e Caribenhas. Estabelecida em 2008, somos a escola de dança Latina mais antiga da ilha e a única com professores de dança Caribenha.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: OpenDance
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@onwidget'
    site: '@onwidget'
    cardType: summary_large_image

i18n:
  language: pt
  textDirection: ltr

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
